### PR TITLE
Using NodeLinter

### PR DESCRIPTION
**Pull request by geta6**
I want to exec jscs from `./node_modules/.bin/jscs`.

### CODE REVIEW

**Comment by levacic** [comment]
Please merge this PR.

**Comment by MannyC** [comment]
Be great to get this merged

**Comment by levacic** [comment]
@groteworld Don't know who else to ping as you seem to be the only active maintainer of the main SublimeLinter3 plugin - so could you take a look at this, since it's an important issue for correctly linting projects using different jscs versions?

**Comment by groteworld** [comment]
Thanks for the nudge. Sorry for the wait.

**Pull request merged**
